services:
  mysqldb:
    image: mysql:8.0
    platform: linux/x86_64
    container_name: mysqlcontainer
    restart: always
    ports:
      - 3306:3306
      - 33060:33060
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      SERVICE_TAGS: prod
      SERVICE_NAME: mysqldb
    networks:
      - internalnet

  nodeapp:
    container_name: nodeappcontainer
    build: ./backend
    image: nodeapp:v1
    working_dir: /UR-backend
    volumes:
      - ./backend/src:/UR-backend/src
    ports:
      - 8080:8080
    expose:
      - 8080
    environment:
      SERVICE_TAGS: prod
      SERVICE_NAME: nodeappservice
    depends_on:
      - mysqldb
    networks:
      - internalnet

  reactapp:
    container_name: reactappcontainer
    build: ./frontend
    image: reactapp:v1
    working_dir: /UR-frontend
    volumes:
      - ./frontend/src:/UR-frontend/src
    ports:
      - 3000:3000
    expose:
      - 3000
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge
