services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqlcontainer
    command: --init-file /docker-entrypoint-initdb.d/0_init.sql
    restart: always
    volumes:
      - ./backend/dbinit/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - $HOME/database:/var/lib/mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: usersdb
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      SERVICE_TAGS: prod
      SERVICE_NAME: mysqldb
    networks:
      - internalnet

  nodeapp:
    container_name: nodeappcontainer
    build: ./backend
    image: nodeapp:v1
    working_dir: /UR-backend
    volumes:
      - ./backend/src:/UR-backend/src
    ports:
      - 8080:8080
    expose:
      - 8080
    environment:
      DB_HOST: mysqldb
      DB_PORT: 3306
      DB_USER: 'root'
      DB_PASSWORD: 'password'
      DB_NAME: usersdb
      DB_CONNECTION_LIMIT: 20
      SERVICE_TAGS: prod
      SERVICE_NAME: nodeappservice
    depends_on:
      - mysqldb
    networks:
      - internalnet
  reactapp:
    container_name: reactappcontainer
    build: ./frontend
    image: reactapp:v1
    working_dir: /UR-frontend
    volumes:
      - ./frontend/src:/UR-frontend/src
    ports:
      - 3000:3000
    expose:
      - 3000
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge
